### PR TITLE
Upgrade to ember-template-compiler 1.9

### PR DESCRIPTION
**Pull request by kenips**
should be sufficient?

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by elucid** [comment]
Shouldn't this include a version bump so that people can still use the previous code with pre-handlebars 2 apps?

**Comment by kenips** [comment]
I was going to ask - not sure if bump with change was preferred. Previous release should be tagged at least to let people stay on old handlebars.

**Comment by rwjblue** [comment]
False as a second param is compat with both old and new.

**Comment by elucid** [comment]
Yes that call is fine, but ember-template-compiler 1.9 only works with Handlebars 2

**Comment by rwjblue** [comment]
Ahh, I see what you mean (sorry for being dense). Ya, this will require a package version bump.

**Pull request merged**
